### ISSUE TITLE
Site has a redirect loop

### ISSUE THREAD

**Issue by afeld** [sinatra/sinatra.github.com#171] opened 2015-11-15 01:27 UTC
Tried from a couple different internet connections, just to make sure it wasn't the CDN thinking I was an attacker or something.

**Comment by afeld** [comment] 2015-11-15 01:29
Ah, just saw this:

https://twitter.com/kgrz/status/665602299234926592

That sucks, sorry :crying_cat_face:

**Comment by kgrz** [comment] 2016-03-09 07:21
Closing this since the problem is fixed

**Closed by kgrz** 2016-03-09 07:21 UTC
